### ISSUE TITLE
Hello, I have several questions regarding your code:

### ISSUE THREAD

**Issue by HolyLin990604** [omarseleem92/Urban_flooding#1]
Hello, I have several questions regarding your code:
1. In the "1- Generate images from points and split the polygons." code, it requires `.shp` files, but you have not provided these `.shp` files.
2. In the "3- Read_cutted_images" code, you mentioned that there are fourteen predictive features including DEM, SDepth, WDepth, TWI, CN, TPI, Cos_Aspect, Sin_Aspect, Curvature, DEML, Flow_acc, Slope, Roughness, RainDepth, but you have only provided data for twelve predictive features.

**Comment by omarseleem92** [comment]
Hi,

1- The point shapefile contains randomly generated points within the study area, which you can create either in Python or using GIS software.

2- We used twelve predictive features to train the model,  the cosine and sine of the aspect as two separate features to account for the cyclic nature of flow direction (Löwe et al., 2021). Therefore, to train the model, you’ll need twelve rasters plus rainfall data. The link includes the twelve rasters, while the code generates rainfall data randomly and prepare the WDepth images based on this rainfall.

As a result:

X (predictive features): a 13-channel image composed of DEM, SDepth, TWI, CN, TPI, Cos_Aspect, Sin_Aspect, Curvature, DEML, Flow_acc, Slope, Roughness, and rainfall.
Y (predictions): a 1-channel image representing WDepth.

It is explained in details in the paper: https://nhess.copernicus.org/articles/23/809/2023/nhess-23-809-2023.pdf

**Comment by HolyLin990604** [comment]
> 你好
> 
> 1- 点 shapefile 包含在研究区域内随机生成的点，您可以在 Python 中或使用 GIS 软件创建这些点。
> 
> 2- 我们使用了 12 个预测特征来训练模型，方面的余弦和正弦作为两个单独的特征来解释流向的循环性质（Löwe 等人，2021 年）。因此，要训练模型，您需要 12 个栅格和降雨数据。该链接包括 12 个栅格，而代码会随机生成降雨数据，并根据此降雨量准备 WDepth 影像。
> 
> 结果：
> 
> X（预测特征）：由 DEM、SDepth、TWI、CN、TPI、Cos_Aspect、Sin_Aspect、曲率、DEML、Flow_acc、斜率、粗糙度和降雨组成的 13 通道图像。 Y （predictions）：表示 WDepth 的 1 通道图像。
> 
> 论文中对此进行了详细解释：https://nhess.copernicus.org/articles/23/809/2023/nhess-23-809-2023.pdf

thanks a lot!!!!!!!🩷
